# -*- coding: utf-8 -*-
"""gridsearch_svm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14RxiSUQb6oEHCOXA4YDKlj-6StX9YTg1
"""

import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

from google.colab import drive
drive.mount('/content/drive')

dataset = pd.read_csv("/content/drive/MyDrive/dataset_pre_processed.csv", dtype={"Class": int})
partA, partB = train_test_split(dataset, test_size=0.8)
y = partA["CLASS_LABEL"]
X = partA.drop("CLASS_LABEL", axis=1)

dataset = dataset[['NumDots', 'SubdomainLevel', 'PathLevel', 'UrlLength', 'NumDash',
       'NumDashInHostname', 'TildeSymbol', 'NumUnderscore', 'NumPercent',
       'NumQueryComponents', 'NumAmpersand', 'NumNumericChars',
       'DomainInSubdomains', 'DomainInPaths', 'HttpsInHostname', 'PathLength',
       'QueryLength', 'NumSensitiveWords', 'PctExtHyperlinks',
       'PctExtResourceUrls', 'InsecureForms', 'RelativeFormAction',
       'AbnormalFormAction', 'PctNullSelfRedirectHyperlinks',
       'FrequentDomainNameMismatch', 'PopUpWindow', 'SubmitInfoToEmail',
       'IframeOrFrame', 'SubdomainLevelRT', 'UrlLengthRT',
       'PctExtResourceUrlsRT', 'ExtMetaScriptLinkRT',
       'PctExtNullSelfRedirectHyperlinksRT','CLASS_LABEL']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

param_grid = {
    'kernel': ['linear', 'poly', 'rbf'],
    'C': [0.1, 1, 10, 100, 1000],
    'gamma': ['scale', 'auto', 1, 0.1, 0.01, 0.001, 0.0001],
}

svm = svm.SVC()

grid_search = GridSearchCV(svm, param_grid, cv=5)

grid_search.fit(X_train, y_train)

print("Melhores parâmetros encontrados:")
print(grid_search.best_params_)

accuracy = grid_search.score(X_test, y_test)
print("Acurácia do modelo nos dados de teste:", accuracy)