# -*- coding: utf-8 -*-
"""pre_processamento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L7xLTekaZDjrxCcFZ9Aa3ydJKB-Hsg3g
"""

#Bibliotecas necessárias

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler

df = pd.read_csv('/content/drive/MyDrive/Phishing_Legitimate_full.csv', header=0)
df.info()

#Drop coluna id
data = df.drop(columns=['id'])

#Conferir se há dados faltantes
data.isna().sum()

data.info()

#Padronização dos dados
scaler = MinMaxScaler()

X = data.iloc[0:10000, 0:48]
X_norm = pd.DataFrame(scaler.fit_transform(X))

#Adicionar Label para o Dataframe e Redefinir o nome das colunas
X_norm['CLASS_LABEL'] = data['CLASS_LABEL']
X_norm.columns=data.columns
X_norm.describe()

# Calculando a matriz de correlação
correlation_matrix = df.corr()

# Gerando o heatmap
plt.figure(figsize=(8, 6))
heatmap = sns.heatmap(correlation_matrix, cmap='coolwarm', vmin=-1, vmax=1)
heatmap.set_xticklabels([])
heatmap.set_yticklabels([])
heatmap.tick_params(left=False, bottom=False)
plt.title("Heatmap de correlação do dataset inicial")
plt.xlabel('Features')
plt.ylabel('Features')
plt.show()

X_norm.to_csv('dataset_pre_processed.csv', index=False)